version: "3"

services:
  shark:
    build: .
    image: zhaoyu/cmu15213:1.0
    container_name: cmu-15213
    volumes:
      - ./labs:/usr/src/app/
    restart: "no"
    stdin_open: true  # --interactive Keep STDIN open even if not attached (docker exec -i)
    tty: true         # --tty Allocate a pseudo-TTY (docker exec -t)
    security_opt:
      - seccomp:unconfined
    cap_add:
      - SYS_PTRACE
    